services:
  siteb-p3-backend:
    build:
      args:
        - NODE_ENV=development
      context: backend
    command: npm run start-watch
    environment:
      - DATABASE_DB=example
      - DATABASE_USER=root
      - DATABASE_PASSWORD=/run/secrets/db-password
      - DATABASE_HOST=db
      - NODE_ENV=development
    secrets:
      - db-password
    networks:
      - back-net
      - public-net
    depends_on:
      - db
  db:
    image: mysql:8.0.27
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data2:/var/lib/mysql
    networks:
      - back-net
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

networks:
  back-net:
  public-net:
    name: proxy-network
    external: true

secrets:
  db-password:
    file: db/password.txt

volumes:
  db-data2:
