services:
  db:
    image: mysql:8
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - back-net
    environment:
      - MYSQL_DATABASE=example
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password

  siteb-p2-backend:
    build:
      context: backend
    restart: always
    secrets:
      - db-password
    networks:
      - back-net
      - public-net
    depends_on:
      - db

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  back-net:
  public-net:
    name: proxy-network
    external: true
